### ISSUE TITLE
v.1.0.2 very slow updating

### ISSUE THREAD

**Issue by Jonwicks25** [MatthewRuddy/displaytweets#4] opened 2013-06-20 15:06 UTC
Seems to take several hours to display a new tweet? Unless you go into the settings and click save then the tweet feed instantly updates.

**Comment by MatthewRuddy** [comment] 2013-06-21 13:32
Should be resolved with v1.0.3 (just uploaded now). Tweets should now update every 5 minutes as intended :)

**Closed as completed by MatthewRuddy** 2013-06-21 13:32 UTC
